# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: Docs

on:
  push:
    branches: ["main"]

jobs:
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: "3.12"
      - name: Install system-level dependencies
        run: sudo apt-get install -y pandoc
      - name: Auto-generate APIDOC sources
        run: make -C docs apidoc
      - name: Create docs
        env:
          SPHINXOPTS: ${{ github.ref != 'refs/heads/main' && '-W' || '' }}
        run: make -C docs html
      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: docs/build/html
          if-no-files-found: error
          retention-days: 5
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
